### ISSUE TITLE
no matching toolchains found for types //rules:toolchain_type

### ISSUE THREAD

**Issue by deceivingrakesh** [simuons/rules_clojure#7] opened 2020-05-26 19:15 UTC
When I try to run the command
bazel build //tests:library

I'm getting this error.
ERROR: While resolving toolchains for target //tests:library: no matching toolchains found for types //rules:toolchain_type

I'm running this from the root folder of "rules_clojure" 
Am I doing something wrong , I couldn't figure how to build .clj files from this rules .

Build label: 3.0.0-homebrew

Thanks for your help

**Comment by simuons** [comment] 2020-07-16 07:37
Hi. Sorry for delay.
I think it is fixed now by https://github.com/simuons/rules_clojure/commit/5da04403eb06df5c1b83684d64ab237a8ce0061d
You have to add `register_toolchains("@rules_clojure//rules:clojure_toolchain")` to WORKSPACE
I didn't figure out root cause yet but I'll do it later. 
Hope it will work for you. I would appreciate if you could update if it works for you.

**Closed as completed** 2020-08-14 08:34 UTC
